# Generated by Django 5.2.7 on 2025-11-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempozika',
            name='tempozin',
        ),
        migrations.AddField(
            model_name='tempozika',
            name='tempoAtivo',
            field=models.IntegerField(default=0),
        ),
    ]
