# Generated by Django 5.2.7 on 2025-11-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_remove_tempozika_tempozin_tempozika_tempoativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempozika',
            name='tempoDesc',
            field=models.IntegerField(default=0),
        ),
    ]
